### PR TITLE
Add fix all for NUnit

### LINKED ISSUE #12: Apply fix in bulk (to the whole file/project/solution)
It would be amazing if the fix could be applied to the whole file/project/solution:

image

Currently, it's sadly not possible:
image

For context, I'd love to migrate our whole solution from native NUnit assertions to Fluent Assertions, but doing it one by one is not an option, as we have a gazillion of usages.

I wonder if that's hard, then maybe just a standalone console app for a one-go migration could be an option? Happy to give it a try myself if you think that would be easier.

Btw, I'm a big fan of your work. Big fan! ;) :)

### PR DESCRIPTION
**Pull request by Greg-Smulko**
Add fix all for NUnit.

Based on https://github.com/meziantou/Meziantou.Analyzer.

Fixes #12.

## Testing

I tested it by registering a local source (`dotnet nuget add source`) and creating a NuGet package (bumped the version and run `dotnet pack`), but it doesn't work. :(
The good news is, that a local version of a package is being used for sure: 
image
Any hints much appreciated 🤷

### CODE REVIEW

**Comment by meziantou** [comment]
Thanks for the contribution!

To add unit tests for the Batch fixer, you may need to copy more code from Meziantou.Analyzer: https://github.com/meziantou/Meziantou.Analyzer/blob/d3f2de4bd6e4969ff53734b5bbe6a2f6ccab8784/tests/Meziantou.Analyzer.Test/Helpers/ProjectBuilder.cs#L281-L284

**Comment by Greg-Smulko** [comment]
Well, thanks. But I'm deeply confused now. XUnit version already has a passing `FixDocumentWithMultipleDiagnostics` test, even though it doesn't implement any custom `FixAllProvider`, just plain `WellKnownFixAllProviders.BatchFixer`.
If I do the same for the NUnit version, the test passes, but in the IDE there is only a single option available still.

**Comment by meziantou** [comment]
Using the published package, VS suggests the batch fixer. The code fixer correctly fixes 2 usages.

image

I'm not sure what's wrong in your case. And I'm not sure a change is needed here.

For the context, the custom batch fixer allows to fix documents where a fix would also edit nodes for another diagnostics. In this case the default batch fixer cannot fix the next diagnostic. The custom batch fixer supports this scenario. In the case of this analyzer, the code fix only changes one statement and doesn't impact other nodes, so the default fixer should be ok.

**Comment by Greg-Smulko** [comment]
Thanks - that really helps. Now I know that's "environmental", rather than not implemented. 🤷 
I'll try VS rather than Rider.

**Comment by Greg-Smulko** [comment]
Well, seems to be a non-issue. 🤦 
Thanks for your time and help!

**Pull request closed without merging**
